steps:
- name: 'ceoloide/platformio-ci:latest'  
  dir: .
  args: ['run']  
artifacts: 
  objects: 
    location: 'gs://gcloud-tutorial-firmwares/$TAG_NAME'
    paths: ['/workspace/.pio/build/nodemcuv2/firmware.bin']